-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- Please make sure to save the file as UTF-8, BUT WITHOUT THE UTF-8 BOM HEADER; ¶
local L = LibStub("AceLocale-3.0"):NewLocale("CooldownToGo", "frFR")
if not L then return end

-- L["Bring up GUI configure dialog"] = true
L["Color"] = "Couleur"
-- L["Configure"] = true
-- L["Delay before cooldown display is activated (useful for button-smashers)"] = true
-- L["Fade time"] = true
-- L["Fade time of the message in seconds"] = true
L["Font"] = "Police"
L["Font outline"] = "Epaisseur de police"
L["Font size"] = "Taille de police"
L["Frame strata"] = "Profondeur de la fenêtre"
-- L["Grace Period"] = true
-- L["Hide minimap icon"] = true
L["High"] = "Au dessus"
-- L["Hold time"] = true
-- L["Ignore"] = true
-- L["Ignore list"] = true
-- L["Ignore next action"] = true
-- L["Items"] = true
L["Lock/Unlock display frame"] = "(Dé)Vérouille la fenêtre"
L["Locked"] = "Vérouillé"
L["Low"] = "En dessous"
L["Medium"] = "Normal"
-- L["Next action will be added to ignore list"] = true
L["None"] = "Aucun"
L["Normal"] = "Normal"
-- L["Petbar"] = true
-- L["Ready"] = true
-- L["Ready time"] = true
-- L["Remove"] = true
-- L["Show the cooldown again this many seconds before the cooldown expires"] = true
-- L["Spell link, item link or petbar:index"] = true
-- L["Spells"] = true
L["Strata"] = "Profondeur"
L["Thick"] = "Epais"
-- L["Time to hold the message in seconds"] = true
-- L["added %s to ignore list"] = true
-- L["removed %s from ignore list"] = true
-- L["|cffeda55fControl + Left Click|r to lock frame"] = true
-- L["|cffeda55fDrag|r to move the frame"] = true
-- L["|cffeda55fLeft Click|r to lock/unlock frame"] = true
-- L["|cffeda55fRight Click|r to open the configuration window"] = true
-- L["|cffeda55fShift + Left Click|r to ignore next action"] = true
