-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- Please make sure to save the file as UTF-8, BUT WITHOUT THE UTF-8 BOM HEADER; ¶
local L = LibStub("AceLocale-3.0"):NewLocale("CooldownToGo", "ruRU")
if not L then return end

-- L["Bring up GUI configure dialog"] = true
L["Color"] = "색상"
-- L["Configure"] = true
-- L["Delay before cooldown display is activated (useful for button-smashers)"] = true
-- L["Fade time"] = true
-- L["Fade time of the message in seconds"] = true
L["Font"] = "글꼴"
L["Font outline"] = "글꼴 윤각"
L["Font size"] = "글꼴 크기"
L["Frame strata"] = "창 우선순위"
-- L["Grace Period"] = true
-- L["Hide minimap icon"] = true
L["High"] = "높음"
-- L["Hold time"] = true
-- L["Ignore"] = true
-- L["Ignore list"] = true
-- L["Ignore next action"] = true
-- L["Items"] = true
L["Lock/Unlock display frame"] = "표시 창을 고정시키거나 이동시킵니다."
L["Locked"] = "잠금"
L["Low"] = "낮음"
L["Medium"] = "중간"
-- L["Next action will be added to ignore list"] = true
L["None"] = "없음"
L["Normal"] = "보통"
-- L["Petbar"] = true
-- L["Ready"] = true
-- L["Ready time"] = true
-- L["Remove"] = true
-- L["Show the cooldown again this many seconds before the cooldown expires"] = true
-- L["Spell link, item link or petbar:index"] = true
-- L["Spells"] = true
L["Strata"] = "우선순위"
L["Thick"] = "굵게"
-- L["Time to hold the message in seconds"] = true
-- L["added %s to ignore list"] = true
-- L["removed %s from ignore list"] = true
-- L["|cffeda55fControl + Left Click|r to lock frame"] = true
-- L["|cffeda55fDrag|r to move the frame"] = true
-- L["|cffeda55fLeft Click|r to lock/unlock frame"] = true
-- L["|cffeda55fRight Click|r to open the configuration window"] = true
-- L["|cffeda55fShift + Left Click|r to ignore next action"] = true
