-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- This is the base locale; values can be "true" so they default to their key, or any string to override that behaviour.
local L = LibStub("AceLocale-3.0"):NewLocale("CooldownToGo", "enUS", true)


L["Next action will be added to ignore list"] = "Next action will be added to ignore list"
L["Ready"] = "Ready"
L["added %s to ignore list"] = "added %s to ignore list"
L["removed %s from ignore list"] = "removed %s from ignore list"
L["|cffeda55fControl + Left Click|r to lock frame"] = "|cffeda55fControl + Left Click|r to lock frame"
L["|cffeda55fDrag|r to move the frame"] = "|cffeda55fDrag|r to move the frame"
L["|cffeda55fLeft Click|r to lock/unlock frame"] = "|cffeda55fLeft Click|r to lock/unlock frame"
L["|cffeda55fRight Click|r to open the configuration window"] = "|cffeda55fRight Click|r to open the configuration window"
L["|cffeda55fShift + Left Click|r to ignore next action"] = "|cffeda55fShift + Left Click|r to ignore next action"
